### ISSUE TITLE
Add GitHub Action to check broken links in documentation.

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#102]
URLs often stop working as time goes by so having an automated way of monitoring for those and flagging them to be sorted is useful. 

A handy [GitHub Action to check broken links](https://github.com/marketplace/actions/broken-link-checker-action) is readily available to be implemented [checking MUSE documentation deployed in Read The Docs](https://muse-os.readthedocs.io/en/latest/).

**Comment by dc2917** [comment]
I'll tackle this

**Comment by dalonsoa** [comment]
If the one running doesn't work, try this one: https://github.com/ruzickap/action-my-broken-link-checker

It will not create issues automatically for each broken link, but it will flag those broken and, importantly, you can have a higher degree of control of the depth of the links that are followed.
