### ISSUE TITLE
Move information from the legacy setup.cfg to pyproject.toml 

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#103]
While definition of the python package and other functionality using `setup.cfg` is perfectly fine, is becoming the legacy approach in favour of `pyproject.toml`. 

While MUSE has some information in `pyproject.toml`, it is mostly empty and all the information is still in `setup.cfg`. This should change. A guide of what a `pyproject.toml` file should look like with all the relevant sections can be found in the [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html). 

Note that there are other tools using `setup.cfg` that should be moved, and others that cannot be moved because they don't know how to use `pyproject.toml` yet (e.g. flake8, which should be moved to its own `.flake8` file).

**Comment by jamesturner246** [comment]
I'll take this.
