### ISSUE TITLE
Add testing in the CI system to cover Python 3.8-3.11, Linux, Windows and MacOS

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#104]
Currently, MUSE only supports, officially, Python 3.8. But that's several years old and that limitation is very restrictive. Moreover, it only run tests in Windows. This issue aims to:

- Setup the CI system (GitHub Actions) to run the tests in Python 3.8-3.11
- Setup the CI system to run tests in all three platforms: Linux, Windows and MacOS

This can be done all at once with a [job matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs). 

As, most likely, some combinations of the above will not work altogether (eg. some dependency does not work in a Python version/platform combination) or will make some tests fail:

- Open an issue for each of the failing combination, indicating the tests that fail and including the log output.
- [Exclude that combination in the testing matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations)

**Comment by TinyMarsh** [comment]
Claiming this issue.

**Comment by dalonsoa** [comment]
OK, so based on https://github.com/ImperialCollegeLondon/MUSE_OS/pull/2, it would seem that 3.8 and 3.9 are ok without further work but newer versions of Python failed in all OS.

One thing at a time, but it would seem that one bottleneck is that MUSE requires `pandas<=1.3` and there are no binary wheels for that one when Python is 3.10 or higher.

I would suggest you skim through the logs for the failing combinations, identify if that is indeed the problem for all of them and open an issue describing the problem. Then, exclude Python 3.10 and 3.11 from the CI and try again. If all checks pass, then remove the specific branch you are working on from the list of branches to run checks for and open the PR finally against the original repository, branch `develop_imperial`.

Does it sound good?
