### ISSUE TITLE
Indicate valid Python versions in pyproject.toml

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#105]
After #103 , #104 

Once valid python versions have been identified - i.e. those that pass all tests for all platforms - the `pyproject.toml` file should be updated to indicate what are those valid python versions, so MUSE can be installed in them. In principle, this should be as simply as modifying the line with `requires-python` with the appropriate values.

**Comment by TinyMarsh** [comment]
Claiming this issue.
