### ISSUE TITLE
Convert muse into a command

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#108]
After #103 

Convert muse into a command, so you can use `muse settings.toml` for running MUSE instead of `python -m muse settings.toml`.

To do this, [an appropriate entry point in `pyproject.toml`](https://setuptools.pypa.io/en/latest/userguide/entry_point.html) must be created pointing (probably) to `muse/__main__.py`, but this will need to be confirmed. 

While it seems like a minor change, the above will enable the use of [pipx](https://pypa.github.io/pipx/), keeping MUSE within its own virtual environment (without the user needing to create it manually), simplifying future updates and allowing it to be used anywhere in the OS.

**Comment by jamesturner246** [comment]
I'll take this.

**Comment by jamesturner246** [comment]
I have a PR addressing this:
https://github.com/ImperialCollegeLondon/MUSE_OS/pull/3

but it is based on the unmerged changes made on
https://github.com/SGIModel/MUSE_OS/pull/118

**Comment by jamesturner246** [comment]
Done. I can't seem to link the PR to this task, but it's #118 .
