### ISSUE TITLE
Update installation instructions for windows

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#109]
As of today, as far as I know, none of the current MUSE dependencies need to be built from source, so [the note for Windows users in the instructions could be removed](https://muse-os.readthedocs.io/en/latest/installing-muse.html) - or moved to a less prominent troubleshooting section to avoid confusion.

**Comment by dalonsoa** [comment]
I'm not totally sure I understand. Is it that the point about installing build tools in Windows is correct for 3.11 but no longer needed for 3.8? 

I'm not entirely surprised. If I remember correctly, those tools were needed because there were no binary wheels for some dependencies under Windows, but I guess that is no longer the case. For what we can see in Ryan's PR, all tests run with Python 3.9, so I guess it is not a problem there either. On Python 3.10, it is to be seen, I guess.

**Comment by dc2917** [comment]
Yes, exactly. 

So I'm wondering whether it's best to either:

1. remove the section about installing Microsoft Visual C++ etc from the documentation and state the requirement to use a Python version where they're not needed, or 
2. let users use whichever Python version they want, but state that they might need Microsoft Visual C++ to build some dependencies if they're on a recent Python version.

**Comment by dalonsoa** [comment]
Let's see what happens with #120. If removing the pinning of pandas (and sorting any other incompatibility) means that build tools are not needed, then I'd go for it.

**Comment by dalonsoa** [comment]
Going back to this one, I think option 2 is better. I'll update the documentation to reflect that an appropriate Python version is required (and providing guidance on how to do so), and remove any reference to MSVC++. It's one thing less to install.
