### ISSUE TITLE
Be explicit on pipx instructions

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#132]
To use a specific Python version with `pipx` in Linux and MacOS do: `pipx install --python $(which python) muse_os`.

**Comment by sgiarols** [comment]
It may be good to also add a note on how to install pipx. In fact, using brew as below

_brew reinstall pipx
pipx ensurepath
pipx --python python3.9 MUSE-OS__

the installation does not proceed giving an error about the python version.

Alternatively, using pip to install pipx, is successful to install muse-os

**Comment by dalonsoa** [comment]
You need to give the full path to the python 3.9 executable, not just python3.9.
