### ISSUE TITLE
Run existing examples as regression tests

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#161]
MUSE has a collection of examples that could be run automatically as regression tests. This will allow to easily identify changes that break full scale simulations - or that results in numerically different results. 

These regression tests should be run automatically (every week, for example, to monitor they are all passing with new updates in dependency versions) as well as part of the normal testing suite with every PR to main or develop - unless they are really, really time consuming. 

This is partly done, already, but some examples are missing: https://github.com/SGIModel/MUSE_OS/blob/f89eb147a6a706fa8f180717f7eefd8336662d0c/tests/test_fullsim_regression.py#L7

**Comment by sgiarols** [comment]
I think these ones should be run altogether all the time that a new PR is made. Currently only a couple of regression tests is left out.

**Comment by dalonsoa** [comment]
There are many dependencies (most of them) for which we do not pin the version to use. So every time we run MUSE in the CI system we are likely to have different versions. Normally, it will be fine or e will spot incompatible versions while doing normal development, but if there is no development for a while, having regular checks might help to spot when we are getting into unsafe territory.
