### ISSUE TITLE
Notebooks should be clear and re-run before building the documentation

### ISSUE THREAD

**Issue by dalonsoa** [SGIModel/MUSE_OS#168]
For the documentation to be relevant and up-to-date with the code, the notebooks it contains should be re-run whenever the documentation is built. If this is not done we might end up with the following problem, where we have currently this[ somewhere in the docs](https://muse-os.readthedocs.io/en/flow_charts/user-guide/add-agent.html):

![image](https://github.com/SGIModel/MUSE_OS/assets/6095790/43b138bd-0160-4d94-89b6-fc69b8151581)

But when we re-run the notebook, we get this:

![image](https://github.com/SGIModel/MUSE_OS/assets/6095790/b3af33ed-6295-44a2-b21b-fd3e9edeceb8)

Or this:

![image](https://github.com/SGIModel/MUSE_OS/assets/6095790/b5af8130-0667-4b0d-895a-82cbf9b51462)

But when re-running we get this:

![image](https://github.com/SGIModel/MUSE_OS/assets/6095790/a076fe97-b990-4a8b-8872-6ded5c7f206f)

I don't know which one is correct, but they are obviously different. 

`nbsphinx` is already in place to display notebooks as documentation, but it only re-run the notebooks that have no output cells. As all of them have output cells, they are never re-run. So, we need a means to clear the output cells of any notebook in the documentation before building it. Ideally, we want to commit only notebooks without outputs as that will make the documentation source cleaner. The exception to this is if there are any notebooks for which we want to keep the output - see [`nbsphinx` docs](https://nbsphinx.readthedocs.io/en/latest/executing-notebooks.html).

Probably we should implement some sort of pre-commit hook to clear the notebooks automatically, but there might be othre options.

@sgiarols , @ahawkes , @martinstringer , do you have any comments or suggestions for this?

**Comment by sgiarols** [comment]
The advanced guide tests should be updated, thus results are different from what is in the documentation.
There is another `[issue](https://github.com/SGIModel/MUSE_OS/issues/99)` about it  The best thing would be to re-build them every time the documentation is built. I think a pre-commit would be a good option. Certainly something done automatically.
If they fail, this is also useful to know, as probably a change in the model has affected them.
