### ISSUE TITLE
Error in MUSE version

### ISSUE THREAD

**Issue by sgiarols** [SGIModel/MUSE_OS#82]
If installation is performed via zip for the first time from the repository, the installation give an error on the license number and stops

**Comment by dalonsoa** [comment]
@sgiarols , is this still relevant?

**Comment by sgiarols** [comment]
@dalonsoa, I repeated the procedure which used to cause the error 
- Download the zip file of the MUSE-OS
- Unzip the folder
- Create an environment
- Write cd MUSE-OS on the terminal
- run "pip install -e ."[dev,doc]"

Now the installation runs smoothly. When I opened the issue, I used to receive an error "version number not found" which made the installation stop. I think [this solved](https://github.com/SGIModel/MUSE_OS/pull/124/files) it.

**Comment by dalonsoa** [comment]
Yeah, from the error message, it looks like it, indeed. Or using the method described just in the line before `[end of output]`, bit in any case not directly downloading the zip file and then installing from there. To be honest, I've never tried to install a repo from a zip file, so I'm not sure how common this error is...

**Comment by sgiarols** [comment]
A troubleshooting section can be useful. We need to think how to structure it. Now there is a FAQ section in the doc...
